# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7021a369d5da0aa778565b98251e62cf861aef68402e077b020bd8b03b18f90e543bd6ee9fd3ae4fd293e831e2d918586d26cb20ca62bc73101bf8f75724b677

test:
  secret_key_base: e3589701c453e84e5627c58588f17cc383d25a09b605627cb53943b7bf961b8a566cf1ea46d3bb9b08acfe0591ce4e780bff405d44d15646da16daee3f3be454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
